# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/latex
install: |-
  sudo /usr/bin/update-depends.sh "$(pwd)/DEPENDS.txt"
merge:
  script: |-
    l3build check
release:
  pre: false
  script: |-
    l3build tag ${tag}
    l3build ctan --show-log-on-error
    texsc
    texqc
    sed -i "s|0000/00/00|$(date +%Y/%m/%d)|g" eolang.pl
    sed -i "s|0.0.0|${tag}|g" eolang.pl
    git commit -am "version set to ${tag}"
    echo 'y' | l3build upload --halt-on-error
