.TH eolang 1 "2024-02-14"
.SH NAME
eolang \- Automated Editor of TeX Files that Use "eolang" Package
.SH SYNOPSIS
eolang [<options>] <.tex source file path> <.tex target file path>
.SH DESCRIPTION
The eolang tool is a Perl script for automatically modifying
TeX files that use "eolang" package, helping them pass post-processing
checks in ACM, arXiv, IEEE, and other publishers.
.SH OPTIONS
Various options apply:
.IP --version
Print the version of the tool
.IP --help
Print the introduction screen
.IP --verbose
Print debugging information too
.SH AUTHOR
Yegor Bugayenko (yegor256@gmail.com)
.SH BUGS
Please log issues on the GitHub homepage:
https://github.com/objectionary/eolang.sty/issues.
.SH SEE ALSO
See eolang.pdf for more details.
